#One Hot Encoding

In [27]:
import numpy as np
import pandas as pd

In [28]:
df=pd.read_csv('/content/sample_data/cars.csv')

In [29]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [30]:
df.shape

(8128, 5)

In [31]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [32]:
df['brand'].nunique()

32

In [33]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [34]:
df.isnull().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [35]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

#1. one hot technique using sklearn

In [56]:
#import library for preprocessing
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(transform='pandas')

In [59]:
ohetranform=ohe.fit_transform(df[['fuel','owner']])

In [60]:
print(ohetranform)

      fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  owner_First Owner  \
0          0.0          1.0       0.0          0.0                1.0
1          0.0          1.0       0.0          0.0                0.0
2          0.0          0.0       0.0          1.0                0.0
3          0.0          1.0       0.0          0.0                1.0
4          0.0          0.0       0.0          1.0                1.0
...        ...          ...       ...          ...                ...
8123       0.0          0.0       0.0          1.0                1.0
8124       0.0          1.0       0.0          0.0                0.0
8125       0.0          1.0       0.0          0.0                1.0
8126       0.0          1.0       0.0          0.0                1.0
8127       0.0          1.0       0.0          0.0                1.0

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                            0.0                 0.0                   0.0
1                            0.0                 1.0                   0.0
2                            0.0                 0.0                   0.0
3                            0.0                 0.0                   0.0
4                            0.0                 0.0                   0.0
...                          ...                 ...                   ...
8123                         0.0                 0.0                   0.0
8124                         1.0                 0.0                   0.0
8125                         0.0                 0.0                   0.0
8126                         0.0                 0.0                   0.0
8127                         0.0                 0.0                   0.0

      owner_Third Owner
0                   0.0
1                   0.0
2                   1.0
3                   0.0
4                   0.0
...                 ...
8123                0.0
8124                0.0
8125                0.0
8126                0.0
8127                0.0

[8128 rows x 9 columns]

In [61]:

df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [63]:
#to show data in correct order
ohetranform.head()

,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

#2. K-1 one hot encoding

In [64]:
#add this data to our df dataset
df=pd.concat([df,ohetranform],axis=1).drop(columns=['fuel','owner'])

In [68]:
df.head(20)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,Skoda,120000,370000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,Honda,140000,158000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,Hyundai,127000,225000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Maruti,120000,130000,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
5,Hyundai,45000,440000,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
6,Maruti,175000,96000,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
7,Maruti,5000,45000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
8,Toyota,90000,350000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9,Ford,169000,200000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10,Renault,68000,500000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,Maruti,100000,92000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
12,Maruti,140000,280000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13,Maruti,80000,200000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
14,Maruti,90000,180000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
15,Mahindra,40000,400000,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
16,Maruti,70000,778000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17,Hyundai,53000,500000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,Maruti,80000,150000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
19,Hyundai,100000,680000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

# LABEL ENCODING

In [12]:
import pandas as pd
import numpy as np

In [14]:
iris_dataset=pd.read_csv('/content/sample_data/iris.csv')

In [15]:
iris_dataset.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

LAbel encoding is apply only on target column like species

In [16]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder() #instance create

In [17]:
print(label_encoder)

LabelEncoder()

object of a class label encoder

In [22]:
iris_dataset['species'] = label_encoder.fit_transform(iris_dataset['species'])

In [24]:
iris_dataset.head(20)

    sepal_length  sepal_width  petal_length  petal_width  species
0            5.1          3.5           1.4          0.2        0
1            4.9          3.0           1.4          0.2        0
2            4.7          3.2           1.3          0.2        0
3            4.6          3.1           1.5          0.2        0
4            5.0          3.6           1.4          0.2        0
5            5.4          3.9           1.7          0.4        0
6            4.6          3.4           1.4          0.3        0
7            5.0          3.4           1.5          0.2        0
8            4.4          2.9           1.4          0.2        0
9            4.9          3.1           1.5          0.1        0
10           5.4          3.7           1.5          0.2        0
11           4.8          3.4           1.6          0.2        0
12           4.8          3.0           1.4          0.1        0
13           4.3          3.0           1.1          0.1        0
14           5.8          4.0           1.2          0.2        0
15           5.7          4.4           1.5          0.4        0
16           5.4          3.9           1.3          0.4        0
17           5.1          3.5           1.4          0.3        0
18           5.7          3.8           1.7          0.3        0
19           5.1          3.8           1.5          0.3        0

In [25]:
#for checking
iris_dataset.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int64
dtype: object

In [26]:
#find unique value from species
iris_dataset['species'].unique()

array([0, 1, 2])